# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('bds.views',
    #url(r'^$',
    #   BdSDashboard,
    #   name='bds_home'),

    #url(r'^sportifs/$',
    #   SportifList.as_view(),
    #   name='sportif_list'),
    #url(r'^sportifs/new$',
    #   NewSportif.as_view(),
    #   name='new_sportif'),
    #url(r'^sportifs/(?P<username>[\w-]+)/$',
    #   ShowSportif.as_view(),
    #   name='show_sportif'),
    #url(r'^sportifs/(?P<username>[\w-]+)/edit$',
    #   EditSportif.as_view(),
    #   name='edit_sportif'),

    #url(r'^sports$',
    #   SportList.as_view(),
    #   name='sport_list'),
    #url(r'^sports/new$',
    #   NewSport.as_view(),
    #   name='new_sport'),
    #url(r'^sports/(?P<name>[\w-]+)/$',
    #   ShowSport.as_view(),
    #   name='show_sport'),
    #url(r'^sports/(?P<name>[\w-]+)/edit$',
    #   ShowSport.as_view(),
    #   name='edit_sport'),

    #url(r'^events$',
    #   EventList.as_view(),
    #   name='event_list'),
    #url(r'^events/new$',
    #   NewEvent.as_view(),
    #   name='new_event'),
    #url(r'^events/(?P<name>[\w-]+)/$',
    #   ShowEvent.as_view(),
    #   name='show_event'),
    #url(r'^events/(?P<name>[\w-]+)/edit$',
    #   ShowEvent.as_view(),
    #   name='edit_event'),
)
